#!/bin/bash
yum install nagios -y
systemctl enable nagios
systemctl start nagios
setenforce 0
yum install -y httpd
systemctl enable httpd
systemctl start httpd
yum install -y nrpe
systemctl enable nrpe
systemctl start nrpe
yum install nagios-plugins-all
htpasswd -c /etc/nagios/passwd nagiosadmin
badpassword
badpassword
yum -y install nagios-plugins-nrpe
apt-get install nagios-nrpe-server nagios-plugins
sed -i 's/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1, 10.142.0.2/g' /etc/nagios/nrpe.cfg
/etc/init.d/nagios-nrpe-server restart
