#!/bin/bash
apt-get install nagios-nrpe-plugin -y
apt-get install nagios-plugins -y
apt-get install nrpe-server nagios-plugins -y
apt-get install nagios-nrpe-server nagios-plugins -y
yum install nrpe-selinux -y
yum install nrpe -y
yum install nagios-plugins-all -y

sed -i 's/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1, 10.142.0.3/g' /etc/nagios/nrpe.cfg
sed -i "s,command[check_hda1]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1,command[check_disk]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p /dev/sda1,g" /etc/nagios/nrpe.cfg

echo "command[check_mem]=/usr/lib/nagios/plugins/check_mem.sh -w 80 -c 90" >> /etc/nagios/nrpe.cfg

chmod +x check_mem.sh
/etc/init.d/nagios-nrpe-server restart
systemctl restart nagios-nrpe-server
