#!/bin/bash

#Provides the ability to copy a file out to all running instances on the network.

#This needs to be run as the Gcloud user.

############# Gets list of active machines. ####################
gcloud compute instances list | grep RUNNING | awk '{print $1}' > active-hosts

############# FOR LOOP #########################################
for line in $(cat active-hosts);

do
#Stores instance name as variable $INSTANCENAME.
  INSTANCENAME=$line

#Copies file to the instance via SSH. 
  gcloud compute scp /home/tjense04/example.txt $INSTANCENAME:/tmp/
  
########## IF STATEMENT - Deals with SSH key creation. #######  
  if [ ! -e /home/tjense04/.ssh/google_compute_engine.pub ]
#Weirdly necessary to create the SSH key.
    badpassword
    badpassword
    y
  fi
######## END OF IF STATEMENT ################################


done
######## END OF FOR LOOP ####################################

#Look towards the SSH to all (https://github.com/Tedtanium/nti-320-linux-monitoring/blob/master/ssh-to-all-example) for better automation syntax should this fail, future me.
